export enum TerminationStatus {
  REQUESTED = 'REQUESTED',
  IN_PROGRESS = 'IN_PROGRESS',
  CLEARANCE_PENDING = 'CLEARANCE_PENDING',
  CLEARANCE_COMPLETED = 'CLEARANCE_COMPLETED',
  FINALIZED = 'FINALIZED',
}
